### ISSUE TITLE
New package version creation fails on required custom metadata fields

### ISSUE THREAD

**Issue by triestelaporte** [forcedotcom/cli#1088]
### Summary

When creating new version of previously managed-released package with required fields on custom metadata, the CLI errors that the fields cannot be changed - even when they are not changed.

### Steps To Reproduce:

I don't have a repos that can easily demonstrate this since it requires a previously managed-released package, but the steps are:

1.  In a version before 7.11 create and release a managed package version.  The package should contain fields on custom metadata types that include `<required>true</required>` tags.
1.  Update CLI to 7.11 (this may not be related, but it's what I did to reach this point)
1.  Try to create new package version using `force:package:version:create`, without changing the metadata for the required fields on the custom metadata.

### Expected result

Package version creation should succeed.

### Actual result

Seeing the following error for every required field on every custom metadata type.

`Value__c: Cannot modify managed object: entity=CustomFieldDefinition, component=<anId>, state=MANAGED_RELEASED, Field: OptionsFlag OptionBit: OptionsFlagRequired Previous Value: true New Value: null\n`

### System Information

{
        "cliVersion": "sfdx-cli/7.110.0",
        "architecture": "win32-x64",
        "nodeVersion": "node-v14.17.3",
        "pluginVersions": [
                "@oclif/plugin-autocomplete 0.3.0 (core)",
                "@oclif/plugin-commands 1.3.0 (core)",
                "@oclif/plugin-help 3.2.2 (core)",
                "@oclif/plugin-not-found 1.2.4 (core)",
                "@oclif/plugin-plugins 1.10.0 (core)",
                "@oclif/plugin-update 1.4.0-3 (core)",
                "@oclif/plugin-warn-if-update-available 1.7.0 (core)",
                "@oclif/plugin-which 1.0.3 (core)",
                "@salesforce/sfdx-plugin-lwc-test 0.1.7 (core)",
                "@salesforce/sfdx-trust 3.6.0 (core)",
                "alias 1.1.10 (core)",
                "apex 0.2.2 (core)",
                "auth 1.7.1 (core)",
                "config 1.2.13 (core)",
                "custom-metadata 1.0.12 (core)",
                "data 0.5.2 (core)",
                "generator 1.1.7 (core)",
                "limits 1.2.1 (core)",
                "org 1.6.7 (core)",
                "salesforce-alm 52.1.0 (core)",
                "schema 1.0.8 (core)",
                "sfdx-cli 7.110.0 (core)",
                "telemetry 1.2.2 (core)",
                "templates 52.1.0 (core)",
                "user 1.3.1 (core)"
        ],
        "osVersion": "Windows_NT 10.0.19044"
}

### Additional information

It's interesting to me that the error message indicates the 'new value' is 'null\n' - yet in the XML the tag for required has a 'true' value, just like before.

The version creation routine does not report any problems on required fields on custom objects.  Just custom metadata types.

**Comment by triestelaporte** [comment]
I downgraded to 7.88.1 and I'm receiving the same error.  So I am not sure this has much to do with the local CLI version.

**Comment by ChloeCoon** [comment]
I'm seeing this same metadata error when running the command  `sfdx force:source:push ` . Nothing about our metadata has changed since the last time we were successfully able to push.

**Comment by dehru** [comment]
I'm glad I'm not alone.  This error started happening today suddenly.  It happens for me when pushing source to a new scratch org for development on a 2GP.

`force-app/main/default/objects/CbAppSetting__mdt/fields/Value__c.field-meta.xml      Cannot modify managed object: entity=CustomFieldDefinition, component=00N3F00000Oqnr7, state=MANAGED_RELEASED, Field: OptionsFlag OptionBit: OptionsFlagRequired Previous Value: true New Value: null (6:13) `

**Comment by triestelaporte** [comment]
For those of you having issues with simple pushes, try building your SOs with the `noancestors` option.  I've had no issues pushing using this method.  It won't help if you need to cut a new package version... but it might get you unstuck.

**Comment by toddhalfpenny** [comment]
For info this has been [raised on the partner chatter](https://partners.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F93A000000HXAq&fId=0D54V00005XOQTx), and this is a response that was posted there.

> It looks like there is a bug that was just logged for this.
I'm going to reach out to the engineering team to get guidance on when an expected fix will go out. I'll report back here on this thread when I have more information.

**Comment by cisano-arelia** [comment]
Creating 2gp package version gave same error for me, even though there were no changes to the custom metadata.
`sfdx-cli/7.110.0 win32-x64 node-v14.17.3`

**Comment by ragimr** [comment]
Got this issue yesterday. Was not able to get rid of ancestor.
But now seems like this bug was fixed.

**Comment by toddhalfpenny** [comment]
There's a post along these lines on the Partner Chatter thread I mentioned above.

> As far as I know, this issue should have been solved now. I asked <...> to check and he confirmed that the issue has been solved for them. FYI

**Comment by cisano-arelia** [comment]
Removing api version from sfdx-project.json and thereby upping the version of the temporary scratch org from 51 to 52 during the build fixed it for me.

`sfdx force:package:version:create -n <ver> -a "Ver <ver>" -t <ver> -x -c -e "<ver desc>" -p <package> 
-f .\config\project-scratch-def.json -w 300`

**Comment by mshanemc** [comment]
Is anyone still seeing this error?  Hoping that server-side fixes from packaging have solved.
