### ISSUE TITLE
sf run function start throws error

### ISSUE THREAD

**Issue by ghost** [forcedotcom/cli#1532]
### `sf run function start` throws error

When i am trying to start my function the below error appears. The message tells me that docker daemon is not running, but as per salesforce docs we do not require docker for locally testing a function.

### Steps To Reproduce:
- run `sf run function start` throws an error saying that ` error during connect: This error may indicate that the docker daemon is not running`. I am using windows 11. Please find my tools version below,

- sfdx version - sfdx-cli/7.151.1
- node version - 16.14.2

### Error log
```
Building queryfunc
ExitError: EEXIT: 0
    at Object.exit (C:\Users\username\AppData\Roaming\npm\node_modules\@salesforce\cli\node_modules\@oclif\errors\lib\index.js:19:11)
    at EventEmitter.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\@salesforce\cli\node_modules\@sf\functions\lib\commands\run\function\start.js:59:30)
    at EventEmitter.emit (node:events:526:28)
    at EventEmitter.emit (node:domain:475:12)
    at Interface.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\@salesforce\cli\node_modules\@heroku\functions-core\dist\benny.js:106:39)
    at Interface.emit (node:events:526:28)
    at Interface.emit (node:domain:475:12)
    at Interface._onLine (node:readline:487:10)
    at Interface._normalWrite (node:readline:661:12)
    at Socket.ondata (node:readline:269:10)
    at Socket.emit (node:events:526:28)
    at Socket.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  oclif: { exit: 0 },
  code: 'EEXIT'
}
Error: Build exited with: failed to fetch builder image 'index.docker.io/heroku/buildpacks:20': error during connect: This error may indicate that the docker daemon is not running.: Post
    "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/images/create?fromImage=heroku%2Fbuildpacks&tag=20": open //./pipe/docker_engine: The system cannot find the file specified.
```

**Comment by ramachandra-mohan** [comment]
I am also facing the same issue. Do we have any workaround for this until we have the fix?

**Comment by skidrowxu** [comment]
I got the same error, anyone knows how to fix it?

**Comment by ramachandra-mohan** [comment]
> I got the same error, anyone knows how to fix it?

I got the same issues and got fixed by authoring the dev hub and sandbox again.

**Comment by ghost** [comment]
Try running the latest versions of sfdx by `sf update` and `sfdx update`. This fixed it for me. Also I got this error only working with Windows not with Linux

**Comment by skidrowxu** [comment]
> ot the same issues and got fixed by authoring the dev hub and sandbox agai

Thanks for reply, but it doesn't work for me....

**Comment by skidrowxu** [comment]
> Try running the latest versions of sfdx by `sf update` and `sfdx update`. This fixed it for me. Also I got this error only working with Windows not with Linux

Yes, my mac is fine, but I still get the same error message after I updated sfdx in my PC. Maybe I just use my macbook then

**Comment by edmorley** [comment]
The `sf run function start` command has not started the function using a container for some time (since ~January, when https://github.com/salesforcecli/plugin-functions/pull/343 landed). To use Docker, one has to explicitly use the legacy `sf run function start container` mode.

If you are seeing Docker related errors running `sf run function start`, it suggests your CLI installation is out of date, or else has an older manually included `plugin-functions` plugin, that is overriding the version of `plugin-functions` that is built into the `sf` CLI.

I would recommend performing a complete uninstall of the Salesforce `sf` and `sfdx` CLI commands using these steps:
https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_uninstall.htm

After that, install the CLI again.
