### ISSUE TITLE
Unable to create a Preview Org

### ISSUE THREAD

**Issue by JodieM** [forcedotcom/cli#260]
I am tying to create a developer org for Spring '20. I have the following in my project-scratch-def.json
`"edition": "Developer",
"release": "Preview",`

I am getting the error
`At this time, we are outside of the preview period. You can create only current release scratch orgs.`

I first tried it after midnight on 4-Jan-2020 PST. 

As per this [link](https://developer.salesforce.com/docs/atlas.en-us.220.0.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_version_selection.htm) it should work after 3-Jan-2020

**Comment by sjurgis** [comment]
Same here.

**Comment by ajw725** [comment]
same here, and it's actually a pretty significant problem for us right now, because we're having some spring 20-related bugs and this makes it much harder to test/debug.

**Comment by shetzel** [comment]
@rrmehta2

**Comment by rrmehta2** [comment]
My team is aware of the bug and we're working on releasing the fix today. I will update this thread as soon as the change is available.

**Comment by rrmehta2** [comment]
The fix has been released and you should now be able to use the version selection feature. Please let me know if you still run into issues.

**Comment by sjurgis** [comment]
Thanks, works fine here!

**Comment by ajw725** [comment]
here too. thanks @rrmehta2 !

**Comment by Mjolnia** [comment]
Hello, 

It seems this bug is not fixed. (Informations about preview periods : [here](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_version_selection.htm))
I have the exacte same problem, but i want to create a Spring 22 scratch org, and the scratch org created without the "release" property is a Summer 22 scratch org.

Any idea ?

Extract of the scratch def file : 


  "edition": "Enterprise",
  "release": "previous",
