### ISSUE TITLE
Retrieving CustomFields causes empty CustomObject to be retrieved

### ISSUE THREAD

**Issue by mdonnalley** [forcedotcom/cli#2865]
### Summary
(NOTE: created from internal slack thread)

With 2.36.8 or later, I am observing that even though I am trying to retrieve a customField, the CLI fetches the Object-meta.xml file as well and its overwriting the existing Object-meta.xml file by removing all the content of it and making it blank(and even though the file exists the state of the file is always fetched as created for object-meta.xml)
```
sf project retrieve start -m CustomField:Account_Plan__c.Products_Services__c -o qa

Retrieving v59.0 metadata from sgupta3@salesforce.com.artlr1qa1 using the v60.0 SOAP API
Preparing retrieve request... Succeeded

Retrieved Source
=====================================================================================================================================================
| State   Name                                 Type         Path                                                                                      
| ─────── ──────────────────────────────────── ──────────── ───────────────────────────────────────────────────────────────────────────────────────── 
| Changed Account_Plan__c.Products_Services__c CustomField  force-app/main/default/objects/Account_Plan__c/fields/Products_Services__c.field-meta.xml 
| Created Account_Plan__c                      CustomObject force-app/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml  
```

```
git diff force-app/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
diff --git a/force-app/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml b/force-app/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
index d175c1808..d254e9b03 100644
--- a/force-app/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
+++ b/force-app/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml
@@ -1,173 +1,2 @@
 <?xml version="1.0" encoding="UTF-8"?>
-<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata">
-    <actionOverrides>
-        <actionName>Accept</actionName>
-        <type>Default</type>
-    </actionOverrides>
-    <actionOverrides>
-        <actionName>Accept</actionName>
-        <formFactor>Large</formFactor>
-        <type>Default</type>
-    </actionOverrides>
-    <actionOverrides>
-        <actionName>Accept</actionName>
-        <formFactor>Small</formFactor>
-        <type>Default</type>
-    </actionOverrides>
-    <actionOverrides>
-        <actionName>CancelEdit</actionName>
-        <type>Default</type>
-    </actionOverrides>
-    <actionOverrides>
-        <actionName>CancelEdit</actionName>
-        <formFactor>Large</formFactor>
-        <type>Default</type>
-    </actionOverrides>
-    <actionOverrides>
-        <actionName>CancelEdit</actionName>
-        <formFactor>Small</formFactor>
-        <type>Default</type>
-    </actionOverrides>
-    <actionOverrides>
-        <actionName>Clone</actionName>
-        <type>Default</type>
-    </actionOverrides>
-    <actionOverrides>
```

### Expected result

Expected `force-app/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml` to not be empty

### Actual result

`force-app/main/default/objects/Account_Plan__c/Account_Plan__c.object-meta.xml` is empty

### System Information

```json
{
  "architecture": "darwin-x64",
  "cliVersion": "@salesforce/cli/2.39.6",
  "nodeVersion": "node-v21.7.1",
  "osVersion": "Darwin 23.4.0",
  "rootPath": "/usr/local/lib/node_modules/@salesforce/cli",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.16 (core)",
    "@oclif/plugin-commands 3.3.1 (core)",
    "@oclif/plugin-help 6.0.21 (core)",
    "@oclif/plugin-not-found 3.1.6 (core)",
    "@oclif/plugin-plugins 5.0.14 (core)",
    "@oclif/plugin-search 1.0.23 (core)",
    "@oclif/plugin-update 4.2.7 (core)",
    "@oclif/plugin-version 2.0.17 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.15 (core)",
    "@oclif/plugin-which 3.1.8 (core)",
    "@salesforce/cli 2.39.6 (core)",
    "apex 3.1.9 (core)",
    "auth 3.6.3 (core)",
    "custom-metadata 3.1.16 (user)",
    "data 3.3.2 (core)",
    "deploy-retrieve 3.6.6 (core)",
    "info 3.2.3 (core)",
    "limits 3.3.4 (core)",
    "marketplace 1.2.4 (core)",
    "org 4.1.3 (core)",
    "packaging 1.26.4 (user)",
    "schema 3.3.4 (core)",
    "settings 2.2.1 (core)",
    "sobject 1.3.6 (core)",
    "source 3.3.3 (core)",
    "telemetry 3.3.4 (core)",
    "templates 56.2.4 (core)",
    "trust 3.6.6 (core)",
    "user 3.5.2 (core)",
    "@salesforce/sfdx-scanner 3.15.0 (user)",
    "sfdmu 4.30.0 (user)",
    "sfdx-git-delta 5.38.2 (user)",
    "vlocityestools 0.24.5 (user)"
  ]
}
```

### Additional Information

Last working version was 2.35.6

**Workaround**:  retrieve the object at the same time you're retrieving the field, or just retrieve the whole object instead of a single field

**Comment by mdonnalley** [comment]
latest-rc (2.41.8) has been patched to include the fix for this

**Comment by shabu74** [comment]
@mdonnalley No Mike. I installed the latest release. It has not been fixed. Still the metadata appears empty.

I have used the following package.xml

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
		<members>Contact.Role__c</members>
		<name>CustomField</name>
	</types>
	<version>58.0</version>
</Package>

Then the metadata of Contate object will be automatically pulled like:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<CustomObject xmlns="http://soap.sforce.com/2006/04/metadata"></CustomObject>
```
It's really annoying and wasting our time. When a new change will be release, it is better to test it well before release rather than breaking the existing feature and forcing sf clients to be beta testers.

**Comment by jshackell-sfdc** [comment]
This issue is fixed in version 2.41.8 -- enjoy!

**Comment by Goobles** [comment]
This issue still exists in 2.42.6
I do not enjoy 😞

**Comment by shabu74** [comment]
This is frustrating. I wonder what they are doing with this. Add new features and breaking existing ones! Never expect this kind of primary school programming from a giant like Salesforce.

**Comment by aheber** [comment]
@shabu74, disclaimer, I'm not a maintainer and not an employee of Salesforce. Just another person who depends on these tools for their daily work.

Your words come across hurtful. If that wasn't your intention I hope you can appreciate how I see them. I can personally attest to the level of care that this team has for their product.

If you feel this isn't going well enough for you then please get involved and find a way to contribute. Testing, code fixes, whatever you think would help get a solution delivered faster.

It is wonderful that this is an open source project and is very special that we have such direct access to the developers and team. Please be respectful, I would be very sad if this team became less available due to poor public interactions. Please remember that your words are read by humans and can have a real impact, positive or negative.

**Comment by Goobles** [comment]
Unproductive comments aside, I installed version 2.41.8 and retried by creating only a field on a custom SObject. The same behavior still happens on that version for me:

Creating just a new field on the Absence__c object in my example, causes the Object xml to be emptied completely:

<img width="1189" alt="image" src="https://github.com/forcedotcom/cli/assets/8776771/b30d74cb-545c-4b05-816d-14c65332d4cf">

All the other changes work as expected:
<img width="744" alt="image" src="https://github.com/forcedotcom/cli/assets/8776771/744488e4-a702-42a3-bcac-a1e28438dec6">
I am running the CLI version that was mentioned earlier claiming to fix the issue:
```
{
  "architecture": "darwin-arm64",
  "cliVersion": "@salesforce/cli/2.41.8",
  "nodeVersion": "node-v20.12.2",
  "osVersion": "Darwin 23.4.0",
  "rootPath": "/Users/gobiusdolhain/.local/share/sf/client/2.41.8-dd2c629",
  "shell": "zsh",
  "pluginVersions": [
    "@oclif/plugin-autocomplete 3.0.17 (core)",
    "@oclif/plugin-commands 3.3.2 (core)",
    "@oclif/plugin-help 6.0.21 (core)",
    "@oclif/plugin-not-found 3.1.8 (core)",
    "@oclif/plugin-plugins 5.0.19 (core)",
    "@oclif/plugin-search 1.0.23 (core)",
    "@oclif/plugin-update 4.2.11 (core)",
    "@oclif/plugin-version 2.0.18 (core)",
    "@oclif/plugin-warn-if-update-available 3.0.16 (core)",
    "@oclif/plugin-which 3.1.9 (core)",
    "@salesforce/cli 2.41.8 (core)",
    "apex 3.1.11 (core)",
    "auth 3.6.9 (core)",
    "data 3.3.4 (core)",
    "deploy-retrieve 3.6.13 (core)",
    "info 3.2.7 (core)",
    "limits 3.3.5 (core)",
    "marketplace 1.2.5 (core)",
    "org 4.1.8 (core)",
    "packaging 2.4.2 (core)",
    "schema 3.3.6 (core)",
    "settings 2.2.6 (core)",
    "signups 2.3.1 (user)",
    "sobject 1.4.1 (core)",
    "source 3.3.9 (core)",
    "telemetry 3.3.5 (core)",
    "templates 56.2.5 (core)",
    "trust 3.6.8 (core)",
    "user 3.5.5 (core)"
  ]
}
```

The same behavior happens on the latest version (2.42.6) as well

PS:

I am using source tracking, so the command I am (or rather Illuminated cloud is) using is `sf project retrieve start` and not a retrieve with a specific field name

**Comment by Goobles** [comment]
I can confirm that it does however work correctly in version 2.35.6 on my setup

**Comment by shabu74** [comment]
Extremely sorry for my words @aheber. I was that much frustrated with the nightmares related to this CLI release changes. When release note says that 'fixed one', something always started to break. That led to the wastage of lot of time during our deployment. Again,  I apologize for my words. I assure it won't happen again. Highly appreciated your patient and sensible reply!

**Comment by cristiand391** [comment]
**EDIT:**
tracking internally as W-15896939

----------------------------------------------------

@Goobles thanks for the details, I'm able to repro the case you mentioned:

custom object already in local project, retrieving the new custom field for the first time nukes the object:

```
➜  dreamhouse-lwc git:(main) ✗ sf -v
@salesforce/cli/2.44.7 darwin-x64 node-v20.10.0
➜  dreamhouse-lwc git:(main) ✗ wc -l force-app/main/default/objects/Lala__c/Lala__c.object-meta.xml
     165 force-app/main/default/objects/Lala__c/Lala__c.object-meta.xml
➜  dreamhouse-lwc git:(main) ✗ ll force-app/main/default/objects/Lala__c/fields/Nana__c.field-meta.xml
ls: force-app/main/default/objects/Lala__c/fields/Nana__c.field-meta.xml: No such file or directory
➜  dreamhouse-lwc git:(main) ✗ sf project retrieve start -m CustomField:Lala__c.Nana__c
Retrieving v60.0 metadata from test-gsenyjcb9fak@example.com using the v60.0 SOAP API
Preparing retrieve request... Succeeded

Retrieved Source
===========================================================================================================
| State   Name            Type         Path
| ─────── ─────────────── ──────────── ────────────────────────────────────────────────────────────────────
| Created Lala__c.Nana__c CustomField  force-app/main/default/objects/Lala__c/fields/Nana__c.field-meta.xml
| Created Lala__c         CustomObject force-app/main/default/objects/Lala__c/Lala__c.object-meta.xml
➜  dreamhouse-lwc git:(main) ✗ wc -l force-app/main/default/objects/Lala__c/Lala__c.object-meta.xml
       2 force-app/main/default/objects/Lala__c/Lala__c.object-meta.xml
```

same scenario on sf v2.35.6
```
➜  dreamhouse-lwc git:(main) ✗ sf -v
 ›   Warning: @salesforce/cli update available from 2.35.6 to 2.42.6.
@salesforce/cli/2.35.6 darwin-x64 node-v20.10.0
➜  dreamhouse-lwc git:(main) ✗ wc -l force-app/main/default/objects/Lala__c/Lala__c.object-meta.xml
     165 force-app/main/default/objects/Lala__c/Lala__c.object-meta.xml
➜  dreamhouse-lwc git:(main) ✗ ll force-app/main/default/objects/Lala__c/fields/Nana__c.field-meta.xml
ls: force-app/main/default/objects/Lala__c/fields/Nana__c.field-meta.xml: No such file or directory
➜  dreamhouse-lwc git:(main) ✗ sf project retrieve start -m CustomField:Lala__c.Nana__c
 ›   Warning: @salesforce/cli update available from 2.35.6 to 2.42.6.
Retrieving v60.0 metadata from test-gsenyjcb9fak@example.com using the v60.0 SOAP API
Preparing retrieve request... Succeeded

Retrieved Source
==========================================================================================================
| State   Name            Type        Path
| ─────── ─────────────── ─────────── ────────────────────────────────────────────────────────────────────
| Created Lala__c.Nana__c CustomField force-app/main/default/objects/Lala__c/fields/Nana__c.field-meta.xml
➜  dreamhouse-lwc git:(main) ✗ wc -l force-app/main/default/objects/Lala__c/Lala__c.object-meta.xml
     165 force-app/main/default/objects/Lala__c/Lala__c.object-meta.xml
```

**Comment by jshackell-sfdc** [comment]
let's try this again. This issue was fixed in version 2.46.6 (June 19, 2024).

**Comment by clifflindberg-bg** [comment]
Issue appears to be back in version 2.78.3

**Comment by schmalli** [comment]
Also present in 2.79.4

**Comment by cristiand391** [comment]
@schmalli can you open a new issue with a small repro?
https://github.com/forcedotcom/cli/issues
