### ISSUE TITLE
Invalid structure while fetching a recordtype which has a business process of the same name

### ISSUE THREAD

**Issue by nickwick76** [forcedotcom/cli#714]
### Summary
Note, this one is similar to issue #579 , which I also experience.

If you have a business process on Opportunity or Case and also have record types with the same name as the business process, then the record types end up in the business process folder when retrieving it with the CLI. This has been verified with VSCode, IntelliJ and CLI standalone.
If you make a change to the record type in the IDE and deploy it, then it gets correctly deployed to the org. But if you make a change in the org and retrieve, the updated recordtype is the one in the business process folder.

### Steps To Reproduce:

1. Create a blank Trailhead org or use an existing org if possible
2. Create an opportunity business process and a record type for that business process that share the same name
3. Create a new project with the below example manifest (version doesn't seem to make a difference)
4. Retrieve from org
5. Check structure in the Opportunity objects and businessProcesses folder

**Package.xml**
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata"> 
    <types>
        <members>Opportunity</members>       
        <name>CustomObject</name>
    </types>
    <version>50.0</version>
</Package>`

### Expected result

There should only be business processes in the businessProcesses folder and recordtypes in the recordTypes folder

### Actual result

There are record types and business processes in the businessProcesses folder and recordtypes in the recordTypes folder

### Additional information

![image](https://user-images.githubusercontent.com/6181405/97544511-01402000-19ca-11eb-875c-c948f2d77973.png)

sfdx-cli/7.77.0-112dd7d412 darwin-x64 node-v12.18.3

@oclif/plugin-autocomplete 0.1.5 (core)
@oclif/plugin-commands 1.3.0 (core)
@oclif/plugin-help 3.2.0 (core)
@oclif/plugin-not-found 1.2.4 (core)
@oclif/plugin-plugins 1.9.1 (core)
@oclif/plugin-update 1.3.10 (core)
@oclif/plugin-warn-if-update-available 1.7.0 (core)
@oclif/plugin-which 1.0.3 (core)
@salesforce/sfdx-trust 3.4.3 (core)
alias 1.1.2 (core)
analytics 1.12.1 (core)
auth 1.3.0 (core)
config 1.1.9 (core)
generator 1.1.3 (core)
salesforcedx 50.2.0 (core)
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7 (core)
├─ salesforce-alm 50.2.0 (core)
├─ custom-metadata 1.0.10 (core)
├─ templates 50.1.0 (core)
└─ apex 0.1.1 (core)
sfdx-cli 7.77.0 (core)

macOS Catalina
Version 10.15.7 (19H2)

**Comment by ghost** [comment]
Just chiming in to say that I've experienced a similar issue. I'm working on a project where some objects have a list view and record type with the same developer name. `sfdx force:source:retrieve` puts the retrieved `recordType-meta.xml` file in the object's `listViews` directory.

**Comment by RensVerhagen** [comment]
Seems the same issue as: #602

**Comment by WillieRuemmele** [comment]
Check out the new [beta source commands](https://github.com/forcedotcom/cli/issues/1057) which should fix this issue!

**Comment by bfalter** [comment]
@WillieRuemmele I am having this same issue; I am using the beta source commands as suggested:
`$ sfdx which force:source:retrieve 
=== force:source:retrieve
plugin: @salesforce/plugin-source
`
I'm still getting my Opportunity RecordType metadata nested within BusinessProcesses. I am retrieving via package.xml

**Comment by mshanemc** [comment]
fixed for `push` in the upcoming version.
